### ISSUE TITLE
Create doc for contributing question suggestion on community dashboard page

### ISSUE THREAD

**Issue by DubeySandeep** [oppia/creator-documentation#11]
We have completed the implementation of creating question suggestions through the community dashboard page. But I found that we don't have the docs for the question suggestion workflow, so we need to add the documentation for the question suggestion workflow.

Note: One can test the UI here: https://oppia-dubeysandeep.appspot.com/community_dashboard
(Send email/message to @DubeySandeep to get review rights, so that one can test review process.)

**Comment by DubeySandeep** [comment]
@audstav, can we prioritize this as we are going to release the community dashboard in the April release? so it would be great if we can add this before the 2nd week of April.

(Assigning you to this issue so that you can reply to this comment)

**Comment by audstav** [comment]
@DubeySandeep  To give an update, I am working on this now and expect to have it complete in the next few days, thanks.

**Comment by audstav** [comment]
Submitted pull request for documentation on Contributing Questions, awaiting review.
